@extends('layouts.management')
@section('content')

<div class="columns">
	<div class="column is-6">
		<h1 class="title">
			Generation Creation
		</h1>
	</div>
</div>

<div class="box">
	<p>
		The code (UUID) will be generated by laravel	
	</p>

	<br>

	<form method="POST" action="/generation/manage">
		@csrf

		<div class="columns">

			<div class="column">
				<label for="is_static">
					Is Static
				</label>
				<select name="is_static" id="is_static" class="input">
					<option value="1" selected>
						Yes
					</option>
					<option value="0">
						No
					</option>
				</select>
			</div>

			<div class="column">
				<label for="amount">
					Coin Amount
				</label>
				<input type="number" name="amount" id="amount" class="input">
			</div>

			<div class="column">
				<label for="shop_id">
					Shop
				</label>
				<select name="shop_id" id="shop_id" class="input">
					<option value="">

					</option>

					@foreach($shops as $shop)
						<option value="{{ $shop->id }}">
							{{ $shop->name }}; {{ $shop->second_name }}
						</option>
					@endforeach
				</select>
			</div>

		</div>

		<input type="submit" name="Create" class="button is-primary">
	</form>
</div>

@endsection